name: "Spotify Echo Agent"
description: "Agent for PR validation with MCP servers (Gemini, Perplexity, Brave, Hyperbrowser)"
secrets:
  - GOOGLE_API_KEY
  - GEMINI_API_KEY
  - PERPLEXITY_API_KEY
  - BRAVE_API
  - HYPERBROWSER_API_KEY

env: {}

setup:
  - run: npx -y playwright install --with-deps

mcpServers:
  gemini:
    type: stdio
    command: npx
    args: ["-y", "gemini-mcp-tool"]
    tools: ["*"]
    env:
      GOOGLE_GEMINI_API_KEY: ${{ secrets.COPILOT_MCP_GEMINI_API_KEY }}
  perplexity:
    type: stdio
    command: npx
    args: ["-y", "@modelcontextprotocol/server-perplexity"]
    tools: ["*"]
    env:
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
  brave-search:
    type: stdio
    command: npx
    args: ["-y", "@modelcontextprotocol/server-brave-search"]
    tools: ["*"]
    env:
      BRAVE_API_KEY: ${{ secrets.COPILOT_MCP_BRAVE_API }}
  hyperbrowser:
    type: stdio
    command: npx
    args: ["-y", "@modelcontextprotocol/server-hyperbrowser"]
    tools: ["*"]
    env:
      HYPERBROWSER_API_KEY: ${{ secrets.HYPERBROWSER_API_KEY }}
